#!/bin/sh

# Check out the appropriate tag depending on arguments
if [ $# -eq 0 ]; then
	deliv_dir=$EIFFEL_SRC/Delivery
else
	deliv_dir=$1
fi

# Check out bitmaps from Build delivery
cp -rf $deliv_dir/esbuilder/bitmaps _Delivery_esbuilder_bitmaps

# Check out files from vision2_tour
cp -rf $deliv_dir/vision2_demo _Delivery_vision2_demo

# Copy template files
cp -r _Delivery_vision2_demo/templates ./

# Copy icons for different widget types across.
cp -r _Delivery_esbuilder_bitmaps ./bitmaps

# Copy icons for standard buttons.
cp _Delivery_vision2_demo/bitmaps/png/documentation.png ./bitmaps/png/
cp _Delivery_vision2_demo/bitmaps/png/testing.png ./bitmaps/png/
cp _Delivery_vision2_demo/bitmaps/png/properties.png ./bitmaps/png/
cp _Delivery_vision2_demo/bitmaps/png/size_down.png ./bitmaps/png/
cp _Delivery_vision2_demo/bitmaps/png/size_up.png ./bitmaps/png/
cp _Delivery_vision2_demo/bitmaps/png/image1.png ./bitmaps/png/
cp _Delivery_vision2_demo/bitmaps/png/image2.png ./bitmaps/png/

cp $EIFFEL_SRC/library/vision2/Clib/default_vision2_icon.ico vision2_demo.ico

# Remove all temporary checked out files.
rm -rf _Delivery_esbuilder_bitmaps
rm -rf _Delivery_vision2_demo
